![[Pasted image 20231004220228.png]]
1. 先写一个异常类,必须让这个类**继承`Exception`**，才能成为一个编译时异常类。或继承RuntimeException运行时异常类。**提供多个构造函数以支持不同的异常信息和异常原因。**
2. 满足某些条件时，可以使用`throw`关键字来抛出自定义异常。
```java
//创建名为`CustomException`的自定义异常类：提供多个构造函数以支持不同的异常信息和异常原因。
public class CustomException extends Exception {

    public CustomException() {
        super();
    }

    public CustomException(String message) {
        super(message);
    }

    public CustomException(String message, Throwable cause) {
        super(message, cause);
    }

    public CustomException(Throwable cause) {
        super(cause);
    }
}

```
```java
//满足某些条件时，可以使用`throw`关键字来抛出自定义异常。
public class CustomExceptionExample {
    
    public static void main(String[] args) {
        try {
            int result = divide(10, 0);
            System.out.println("Result: " + result);
        } catch (CustomException e) {
            System.err.println("CustomException caught: " + e.getMessage());
        }
    }

    public static int divide(int dividend, int divisor) throws CustomException {
        if (divisor == 0) {
            throw new CustomException("Division by zero is not allowed.");
        }
        return dividend / divisor;
    }
}

```
方法内用throw
方法外用throws
**异常处理：**
1. 将异常捕获，将比较友好的信息显示给用户看。（try...catch）
2. 尝试重新执行，看是是否能修复这个问题。（循环+try...catch）